### ISSUE TITLE
Profile: Settings functions(Fingerprint)

### ISSUE THREAD

**Issue by jiangfuyao** [polkawallet-io/polkawallet-RN#108]
#37 -4  
Fingerprint identification is required to open the application.

**Comment by HuanDay** [comment]
Trying to do this feature [#108](https://github.com/polkawallet-io/polkawallet-RN/commit/be11fc262f49a1e2fbd030315e7121e1f05b5c85)

Some ideas before further step:

1.  Should have a seperate passcode page to lock the app if user has already set a passcode. This page will display every time when the app open or from background to foreground. 

2. Passcode can be a 6 digits, not the password when creating an account. This could make it easier to unlock the app with passcode.

3. User can switch between passcode or touch ID (fingerprint or face ID) in settings as their preference.

**Comment by jiangfuyao** [comment]
@hz This has been done in the branch 0.1.9
