### ISSUE TITLE
Code: Decide on code-style. Add ESLint + Prettier + enforce with git hooks.

### ISSUE THREAD

**Issue by StevenJNPearce** [polkawallet-io/polkawallet-RN#110]
Inconsistent code style with little spacing. As more contributors like myself come to this project from gitcoin, I think choosing a style guide and enforcing automatically with ESLint + Prettier + git hooks can improve the readability of the code which will increase productivity of contributors.

**Comment by jiangfuyao** [comment]
@StevenJNPearce Thanks for your suggest, I'll tweak it to make it developer friendly.
