### ISSUE TITLE
Master code compile failed when `react-native run-ios`

### ISSUE THREAD

**Issue by ygmtx** [polkawallet-io/polkawallet-RN#143]
** BUILD FAILED **

The following build commands failed:
        CpResource /Users/Downloads/polkawallet-RN-master/release_ios/main.jsbundle /Users/Downloads/polkawallet-RN-master/ios/build/Polkawallet/Build/Products/Debug-iphonesimulator/Polkawallet.app/main.jsbundle
(1 failure)

**Comment by ygmtx** [comment]
I use curl to create a local main.jsbundle, the project can build successd. But the main.jsbundle is wrong. Loading bundle is always 99%.

**Comment by HuanDay** [comment]
I also have this issue when build the master, [PR-142](https://github.com/polkawallet-io/polkawallet-RN/pull/142) should already fix this one

**Comment by HuanDay** [comment]
This issue can be closed as it was fixed in #142
