### ISSUE TITLE
请问一下，一个新的RN项目，怎么引入Polkadot.js，需要配置哪些文件？

### ISSUE THREAD

**Issue by 452MJ** [polkawallet-io/polkawallet-RN#151]

**Comment by 452MJ** [comment]
弃用自带的ws请求，改用axios的http请求

**Comment by 452MJ** [comment]
参考该项目 [polkadotjsWithReactNative](https://github.com/hashpire/polkadotjsWithReactNative)

**Comment by jiangfuyao** [comment]
and this: <https://github.com/jacogr/pjs-rn-rncli>
