### ISSUE TITLE
Standardize QR code for the address

### ISSUE THREAD

**Issue by maciejhirsz** [polkawallet-io/polkawallet-RN#99]
Hey there, we are all really impressed by what you've put together here!

While there isn't yet an equivalent of [EIP-681](https://eips.ethereum.org/EIPS/eip-681), I think it's sensible to anticipate a similar format to emerge in the future. Therefore I'd propose to include a `substrate:` URI scheme in the QR code with the address that you show:

```
substrate:5GKhf...tmx
```

I'll propose the same for Substrate part of [Universal Offline Signatures](https://github.com/maciejhirsz/uos).

**Comment by jiangfuyao** [comment]
@maciejhirsz  Thanks for Thank you for your guidance. I'll study the problem carefully.
